// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('./components/base/Footer.vue')['default']
    Nav: typeof import('./components/layouts/nav.vue')['default']
  }
}

export { }
